name: flutter_cocktail_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: ^0.13.4
  oxidized: ^5.2.0
  equatable: ^2.0.3
  connectivity_plus: ^2.3.1
  google_fonts: ^3.0.1
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  animations: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.2.0

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

